const size = [
    { id: "xxl-64", label: "XXL || 64" },
    { id: "xxl-63", label: "XXL || 63" },
    { id: "xxl-62", label: "XXL || 62" },
    { id: "xl-61", label: "XL || 61" },
    { id: "xl-60", label: "XL || 60" },
    { id: "xl-59", label: "XL || 59" },
    { id: "l-57", label: "L || 57" },
    { id: "l-56", label: "L || 56" },
    { id: "l-55", label: "L || 55" },
    { id: "m-54", label: "M || 54" },
    { id: "m-53", label: "M || 53" },
    { id: "m-52", label: "M || 52" },
    { id: "s-52", label: "S || 52" },
    { id: "s-51", label: "S || 51" },
    { id: "s-50", label: "S || 50" },
    { id: "xs-49", label: "XS || 49" },
    { id: "xs-48", label: "XS || 48" },
    { id: "xs-47", label: "XS || 47" },
    { id: "xxs-46", label: "XXS || 46" },
    { id: "xxs-45", label: "XXS || 45" },
    { id: "xxs-44", label: "XXS || 44" },
    ];
export default size