const size = [
    { id: "xxl", label: "XXL", category: ["mtb"], all: true },
    { id: "xl;", label: "XL", category: ["mtb"], all: true },
    { id: "l;", label: "L", category: ["mtb"], all: true },
    { id: "m;", label: "M", category: ["mtb"], all: true },
    { id: "s;", label: "S", category: ["mtb"], all: true },
    { id: "xs;", label: "XS", category: ["mtb"], all: true },
    { id: "xxs;", label: "XXS", category: ["mtb"], all: true },
    { id: "xxl-64", label: "64", category: [], all: true },
    { id: "xxl-63", label: "63", category: [], all: true },
    { id: "xxl-62", label: "62", category: [], all: true },
    { id: "xxl-61", label: "61", category: [], all: true },
    { id: "xl-60", label: "60", category: [], all: true },
    { id: "xl-59", label: "59", category: [], all: true },
    { id: "xl-58", label: "58", category: [], all: true },
    { id: "l-57", label: "57", category: [], all: true },
    { id: "l-56", label: "56", category: [], all: true },
    { id: "l-55", label: "55", category: [], all: true },
    { id: "m-54", label: "54", category: [], all: true },
    { id: "m-53", label: "53", category: [], all: true },
    { id: "m-52", label: "52", category: [], all: true },
    { id: "s-52", label: "52", category: [], all: true },
    { id: "s-51", label: "51", category: [], all: true },
    { id: "s-50", label: "50", category: [], all: true },
    { id: "xs-49", label: "49", category: [], all: true },
    { id: "xs-48", label: "48", category: [], all: true },
    { id: "xs-47", label: "47", category: [], all: true },
    { id: "xxs-46", label: "46", category: [], all: true },
    { id: "xxs-45", label: "45", category: [], all: true },
    { id: "xxs-44", label: "44", category: [], all: true },
];

export default size;
